### ISSUE TITLE
Image optimizations

### ISSUE THREAD

**Issue by 0x73706f6f6b** [elisajohnson/elisajohnson.github.io#1]
The site performance is low due to the images not being optimized(images retaining their true sizes). Perhaps using an compression scheme for images like tinyjpg.com or tinypng.com depending on the image type.

**Comment by elisajohnson** [comment]
Thanks for the resources!

**Comment by elisajohnson** [comment]
Should be optimized now :)

**Comment by 0x73706f6f6b** [comment]
:thumbsup:
